/*
 * Beangle, Agile Development Scaffold and Toolkits.
 *
 * Copyright © 2005, The Beangle Software.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.beangle.sas

/** Beangle Sas Version
 *  The logo is generated by http://www.patorjk.com/software/taag/#p=display&f=Graffiti
 * */
object Version {

  val version = "0.6.11"

  def logo:String={
    s"""|   _____
        |  / ____|
        | | (___    __ _  ___
        |  \\___ \\  / _` |/ __|
        |  ____) || (_| |\\__ \\
        | |_____/  \\__,_||___/
        | version ${version}
        |""".stripMargin
  }
}
